# Generated by Django 5.2.7 on 2025-10-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
